import {DatabaseNode, TableNode, Column} from '../components/Dataset';
/**@type {DatabaseNode & {tabs: {
    "CENNIK__GM": TableNode<"ID_cennin_GM"|"CATALOG_NO"|"DESC_GER1"|"DESC_GER2"|"PRICE">,
    "czynność": TableNode<"ID_cynności"|"czynność">,
    "dane_do_zaświadczenie_o_sprawności_inst": TableNode<"ID_typów"|"Producent"|"Typ/Nr"|"E-_"|"67R-_"|"Ważność_legalizacji_zbiornika_do"|"ID_obrotów_mag">,
    "dokumenty_sprzedaży": TableNode<"ID_dokumentu"|"nazwa_dokumentu"|"nr_dokumentu"|"ID_zlecenia"|"data_wystawienia">,
    "dokumenty_sprzedaży_chwilówk": TableNode<"nazwa_dokumentu"|"nr_dokumentu"|"ID_zlecenia"|"data_wystawienia">,
    "dostawcy": TableNode<"ID_dostawcy_-_producenta"|"Nazwa"|"kod_pocztowy"|"miejscowość"|"ulica_nr_domu"|"tel_1"|"tel_2"|"fax"|"konto_bank"|"nr_konta"|"przedstawiciel"|"@-maill"|"NIP"|"otrzymany_rabat_%">,
    "faktura_szczegóły_chwilówka": TableNode<"nazwa_części_lub_czynności"|"jednostka"|"ilość"|"cena_netto"|"numer">,
    "inwentaryzacja": TableNode<"numer_cz"|"ilość"|"data_zapisu"|"rodzaj_dokumentu"|"numer_dokumentu">,
    "inwentaryzacja_nr_3": TableNode<"numer_cz"|"ilość"|"data_zapisu"|"rodzaj_dokumentu"|"numer_dokumentu">,
    "jamar": TableNode<"nazwa_części_lub_czynności"|"jednostka"|"ilość"|"cena_netto"|"numer">,
    "klienci": TableNode<"ID"|"NAZWA"|"MIASTO"|"ULICA"|"KOD_POCZT"|"TELEFON1"|"TELEFON2"|"NIP"|"KTO"|"KIEDY"|"UPUST"|"odbierający_fakturę"|"list"|"aux_info">,
    "liczby_słownie": TableNode<"liczba"|"słownie">,
    "modele_sam": TableNode<"ID_modelu"|"Model:"|"Typ:"|"Nadw:"|"Rok_produkcji:"|"Silnik:"|"Kod:">,
    "nazwy_części": TableNode<"numer_części"|"nazwa_części"|"gtu"|"jednostka"|"grupa"|"VAT"|"ilość_w_opakowaniu_zbiorczym"|"lokalizacja_w_magazynie"|"odpowiedniki">,
    "obroty_magazynowe": TableNode<"ID"|"numer_cz"|"ilość"|"cena_netto"|"data_przyjęcia"|"rodzaj_dokumentu"|"numer_dokumentu"|"cena_netto_sprzedaży">,
    "płace": TableNode<"ID_płac"|"ID_pracownika"|"data"|"kwota"|"podstawa"|"miesiąc_płacenia">,
    "pracownicy": TableNode<"ID_pracownika"|"nazwisko"|"imię"|"inię_II"|"nazwisko_rodowe"|"imię_ojca"|"imię_matki"|"nazwisko_rodowe_matki"|"data_urodzenia"|"miejsce_urodzenia"|"obywatelstwo"|"nr_PESEL"|"nr_NIP"|"ul_i_nr_domu"|"kod"|"miejscowość"|"tel_domowy"|"wykształcenie"|"wykształcenie_uzupełniające"|"dodatkowe_uprawnienia"|"stanowisko">,
    "przyjęcia_PZ": TableNode<"numer_cz"|"ilość"|"cena_netto"|"data_przyjęcia"|"rodzaj_dokumentu"|"numer_dokumentu">,
    "rodzaje_dokumentów": TableNode<"rodzaj_dokumentu">,
    "samochody_klientów": TableNode<"ID"|"kalkulacja"|"marka"|"model"|"nr_rej"|"ID_klienta"|"nr_silnika"|"nr_nadwozia">,
    "sposób_zapłaty": TableNode<"sposób_zapłaty">,
    "sprzedaż": TableNode<"numer_cz"|"ilość"|"cena_netto_sprzedaży"|"cena_netto"|"rodzaj_dokumentu"|"numer_dokumentu"|"data_przyjęcia">,
    "zamówienia_części": TableNode<"numer_części"|"ilość"|"data_zamówienia"|"uwagi_/_przeznaczenie">,
    "zamówienia_części_archiwum": TableNode<"numer_części"|"ilość"|"data_zamówienia"|"data_realizacji"|"uwagi_/_przeznaczenie"|"zlealizowane">,
    "zlecenia_czynności": TableNode<"ID_zlecenia"|"ID_czynności"|"krotność_wykonania"|"cena_netto">,
    "zlecenia_gaz": TableNode<"ID_zlecenia"|"ID_czynności"|"krotność_wykonania"|"cena_netto">,
    "zlecenia_instalacji_gazowej": TableNode<"ID"|"ID_klienta"|"ID_samochodu"|"data_otwarcia"|"data_zamknięcia"|"zysk_z_części"|"zysk_z_robocizny"|"mechanik_prowadzący"|"%_udziału"|"pomocnik_1"|"%_udziału_p1"|"pomocnik_2"|"%_udziału_p2"|"zgłoszone_naprawy"|"uwagi_o_naprawie">,
    "zlecenia_naprawy": TableNode<"ID"|"ID_klienta"|"ID_samochodu"|"data_otwarcia"|"data_zamknięcia"|"nr_faktury"|"platnosc_forma"|"platnosc_data"|"zysk_z_części"|"zysk_z_robocizny"|"mechanik_prowadzący"|"%_udziału"|"pomocnik_1"|"%_udziału_p1"|"pomocnik_2"|"%_udziału_p2"|"zgłoszone_naprawy"|"uwagi_o_naprawie">,
}}}*/
const DB = new DatabaseNode([
    {name: "CENNIK  GM", cols: [
        {"name":"ID cennin GM","type":"INTEGER","attr":"pan"},
        {"name":"CATALOG_NO","type":"LONGTEXT","attr":"nq"},
        {"name":"DESC_GER1","type":"LONGTEXT","attr":""},
        {"name":"DESC_GER2","type":"LONGTEXT","attr":""},
        {"name":"PRICE","type":"DOUBLE","attr":""},
    ]},
    {name: "czynność", cols: [
        {"name":"ID cynności","type":"INTEGER","attr":"pan"},
        {"name":"czynność","type":"LONGTEXT","attr":"nq"},
    ]},
    {name: "dane do zaświadczenie o sprawności inst", cols: [
        {"name":"ID typów","type":"INTEGER","attr":"pan"},
        {"name":"Producent","type":"LONGTEXT","attr":""},
        {"name":"Typ/Nr","type":"LONGTEXT","attr":"n"},
        {"name":"E-_","type":"TINYINT","targ":"3","def":"0","attr":"un"},
        {"name":"67R-_","type":"LONGTEXT","attr":"n"},
        {"name":"Ważność legalizacji zbiornika do","type":"DATETIME","attr":""},
        {"name":"ID obrotów mag","type":"INTEGER","def":"0","attr":"n"},
    ]},
    {name: "dokumenty sprzedaży", cols: [
        {"name":"ID dokumentu","type":"INTEGER","attr":"pan"},
        {"name":"nazwa dokumentu","type":"LONGTEXT","attr":"n"},
        {"name":"nr dokumentu","type":"LONGTEXT","attr":"nq"},
        {"name":"ID zlecenia","type":"INTEGER","def":"0","attr":"n"},
        {"name":"data wystawienia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
    ]},
    {name: "dokumenty sprzedaży chwilówk", cols: [
        {"name":"nazwa dokumentu","type":"LONGTEXT","attr":"n"},
        {"name":"nr dokumentu","type":"LONGTEXT","attr":"nq"},
        {"name":"ID zlecenia","type":"INTEGER","def":"0","attr":"n"},
        {"name":"data wystawienia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
    ]},
    {name: "dostawcy", cols: [
        {"name":"ID dostawcy - producenta","type":"INTEGER","attr":"pan"},
        {"name":"Nazwa","type":"LONGTEXT","attr":"nq"},
        {"name":"kod pocztowy","type":"LONGTEXT","attr":"n"},
        {"name":"miejscowość","type":"LONGTEXT","attr":"n"},
        {"name":"ulica nr domu","type":"LONGTEXT","attr":""},
        {"name":"tel 1","type":"LONGTEXT","attr":""},
        {"name":"tel 2","type":"LONGTEXT","attr":""},
        {"name":"fax","type":"LONGTEXT","attr":""},
        {"name":"konto bank","type":"LONGTEXT","attr":""},
        {"name":"nr konta","type":"LONGTEXT","attr":""},
        {"name":"przedstawiciel","type":"LONGTEXT","attr":""},
        {"name":"@-maill","type":"LONGTEXT","attr":"q"},
        {"name":"NIP","type":"LONGTEXT","attr":""},
        {"name":"otrzymany rabat %","type":"TINYINT","targ":"3","def":"0","attr":"un"},
    ]},
    {name: "faktura szczegóły chwilówka", cols: [
        {"name":"nazwa części lub czynności","type":"LONGTEXT","attr":""},
        {"name":"jednostka","type":"LONGTEXT","attr":""},
        {"name":"ilość","type":"FLOAT","def":"0","attr":""},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"numer","type":"LONGTEXT","attr":""},
    ]},
    {name: "inwentaryzacja", cols: [
        {"name":"numer cz","type":"LONGTEXT","attr":"n"},
        {"name":"ilość","type":"DOUBLE","attr":""},
        {"name":"data zapisu","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":"n"},
        {"name":"rodzaj dokumentu","type":"LONGTEXT","def":"'inwen'","attr":"n"},
        {"name":"numer dokumentu","type":"INTEGER","def":"4","attr":""},
    ]},
    {name: "inwentaryzacja nr 3", cols: [
        {"name":"numer cz","type":"LONGTEXT","attr":"n"},
        {"name":"ilość","type":"DOUBLE","attr":""},
        {"name":"data zapisu","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":"n"},
        {"name":"rodzaj dokumentu","type":"LONGTEXT","def":"'inwen'","attr":"n"},
        {"name":"numer dokumentu","type":"INTEGER","def":"3","attr":""},
    ]},
    {name: "jamar", cols: [
        {"name":"nazwa części lub czynności","type":"LONGTEXT","attr":""},
        {"name":"jednostka","type":"LONGTEXT","attr":""},
        {"name":"ilość","type":"FLOAT","def":"0","attr":""},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"numer","type":"LONGTEXT","attr":""},
    ]},
    {name: "klienci", cols: [
        {"name":"ID","type":"INTEGER","attr":"pan"},
        {"name":"NAZWA","type":"LONGTEXT","attr":"nq"},
        {"name":"MIASTO","type":"LONGTEXT","attr":"n"},
        {"name":"ULICA","type":"LONGTEXT","attr":"n"},
        {"name":"KOD_POCZT","type":"LONGTEXT","attr":"n"},
        {"name":"TELEFON1","type":"LONGTEXT","attr":""},
        {"name":"TELEFON2","type":"LONGTEXT","attr":""},
        {"name":"NIP","type":"LONGTEXT","attr":"q"},
        {"name":"KTO","type":"LONGTEXT","attr":""},
        {"name":"KIEDY","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
        {"name":"UPUST","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"odbierający fakturę","type":"LONGTEXT","attr":""},
        {"name":"list","type":"TINYINT","targ":"1","attr":""},
        {"name":"aux_info","type":"LONGTEXT","def":"NULL","attr":""},
    ]},
    {name: "liczby słownie", cols: [
        {"name":"liczba","type":"DOUBLE","attr":"pn"},
        {"name":"słownie","type":"LONGTEXT","attr":"nq"},
    ]},
    {name: "modele sam", cols: [
        {"name":"ID modelu","type":"INTEGER","attr":"pan"},
        {"name":"Model:","type":"LONGTEXT","attr":""},
        {"name":"Typ:","type":"LONGTEXT","attr":"q"},
        {"name":"Nadw:","type":"LONGTEXT","attr":""},
        {"name":"Rok produkcji:","type":"LONGTEXT","attr":""},
        {"name":"Silnik:","type":"LONGTEXT","attr":""},
        {"name":"Kod:","type":"LONGTEXT","attr":""},
    ]},
    {name: "nazwy części", cols: [
        {"name":"numer części","type":"LONGTEXT","attr":"pnq"},
        {"name":"nazwa części","type":"LONGTEXT","attr":""},
        {"name":"gtu","type":"LONGTEXT","attr":""},
        {"name":"jednostka","type":"LONGTEXT","def":"'szt.'","attr":""},
        {"name":"grupa","type":"FLOAT","def":"0","attr":""},
        {"name":"VAT","type":"FLOAT","def":".22","attr":""},
        {"name":"ilość w opakowaniu zbiorczym","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"lokalizacja w magazynie","type":"LONGTEXT","attr":""},
        {"name":"odpowiedniki","type":"LONGTEXT","attr":""},
    ]},
    {name: "obroty magazynowe", cols: [
        {"name":"ID","type":"INTEGER","attr":"pan"},
        {"name":"numer cz","type":"LONGTEXT","attr":"n"},
        {"name":"ilość","type":"DOUBLE","attr":"n"},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"data przyjęcia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":"n"},
        {"name":"rodzaj dokumentu","type":"LONGTEXT","attr":"n"},
        {"name":"numer dokumentu","type":"INTEGER","def":"0","attr":""},
        {"name":"cena netto sprzedaży","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
    ]},
    {name: "płace", cols: [
        {"name":"ID płac","type":"INTEGER","attr":"pan"},
        {"name":"ID pracownika","type":"INTEGER","def":"0","attr":""},
        {"name":"data","type":"LONGTEXT","attr":""},
        {"name":"kwota","type":"FLOAT","def":"0","attr":""},
        {"name":"podstawa","type":"LONGTEXT","attr":""},
        {"name":"miesiąc płacenia","type":"DATETIME","attr":""},
    ]},
    {name: "pracownicy", cols: [
        {"name":"ID pracownika","type":"INTEGER","attr":"pan"},
        {"name":"nazwisko","type":"LONGTEXT","attr":""},
        {"name":"imię","type":"LONGTEXT","attr":""},
        {"name":"inię II","type":"LONGTEXT","attr":""},
        {"name":"nazwisko rodowe","type":"LONGTEXT","attr":""},
        {"name":"imię ojca","type":"LONGTEXT","attr":""},
        {"name":"imię matki","type":"LONGTEXT","attr":""},
        {"name":"nazwisko rodowe matki","type":"LONGTEXT","attr":""},
        {"name":"data urodzenia","type":"DATETIME","attr":"n"},
        {"name":"miejsce urodzenia","type":"LONGTEXT","attr":""},
        {"name":"obywatelstwo","type":"LONGTEXT","attr":""},
        {"name":"nr PESEL","type":"LONGTEXT","attr":""},
        {"name":"nr NIP","type":"LONGTEXT","attr":""},
        {"name":"ul i nr domu","type":"LONGTEXT","attr":""},
        {"name":"kod","type":"LONGTEXT","attr":""},
        {"name":"miejscowość","type":"LONGTEXT","attr":""},
        {"name":"tel domowy","type":"LONGTEXT","attr":""},
        {"name":"wykształcenie","type":"LONGTEXT","attr":""},
        {"name":"wykształcenie uzupełniające","type":"LONGTEXT","attr":""},
        {"name":"dodatkowe uprawnienia","type":"LONGTEXT","attr":""},
        {"name":"stanowisko","type":"LONGTEXT","attr":""},
    ]},
    {name: "przyjęcia PZ", cols: [
        {"name":"numer cz","type":"LONGTEXT","attr":"n"},
        {"name":"ilość","type":"DOUBLE","attr":""},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"data przyjęcia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":"n"},
        {"name":"rodzaj dokumentu","type":"LONGTEXT","def":"'dosta'","attr":"n"},
        {"name":"numer dokumentu","type":"INTEGER","def":"0","attr":""},
    ]},
    {name: "rodzaje dokumentów", cols: [
        {"name":"rodzaj dokumentu","type":"LONGTEXT","attr":""},
    ]},
    {name: "samochody klientów", cols: [
        {"name":"ID","type":"INTEGER","attr":"pan"},
        {"name":"kalkulacja","type":"INTEGER","def":"0","attr":""},
        {"name":"marka","type":"LONGTEXT","attr":"n"},
        {"name":"model","type":"LONGTEXT","attr":"n"},
        {"name":"nr rej","type":"LONGTEXT","attr":"n"},
        {"name":"ID klienta","type":"INTEGER","def":"0","attr":""},
        {"name":"nr silnika","type":"LONGTEXT","attr":"n"},
        {"name":"nr nadwozia","type":"LONGTEXT","attr":"n"},
    ]},
    {name: "sposób zapłaty", cols: [
        {"name":"sposób zapłaty","type":"LONGTEXT","attr":""},
    ]},
    {name: "sprzedaż", cols: [
        {"name":"numer cz","type":"LONGTEXT","attr":"nq"},
        {"name":"ilość","type":"DOUBLE","attr":""},
        {"name":"cena netto sprzedaży","type":"DECIMAL","targ":"19,4","attr":""},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"rodzaj dokumentu","type":"LONGTEXT","attr":"n"},
        {"name":"numer dokumentu","type":"INTEGER","attr":"n"},
        {"name":"data przyjęcia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":"n"},
    ]},
    {name: "zamówienia części", cols: [
        {"name":"numer części","type":"LONGTEXT","attr":""},
        {"name":"ilość","type":"DOUBLE","def":"0","attr":""},
        {"name":"data zamówienia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
        {"name":"uwagi / przeznaczenie","type":"LONGTEXT","attr":""},
    ]},
    {name: "zamówienia części archiwum", cols: [
        {"name":"numer części","type":"LONGTEXT","attr":""},
        {"name":"ilość","type":"DOUBLE","def":"0","attr":""},
        {"name":"data zamówienia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
        {"name":"data realizacji","type":"DATETIME","attr":""},
        {"name":"uwagi / przeznaczenie","type":"LONGTEXT","attr":""},
        {"name":"zlealizowane","type":"TINYINT","targ":"1","attr":""},
    ]},
    {name: "zlecenia czynności", cols: [
        {"name":"ID zlecenia","type":"INTEGER","def":"0","attr":""},
        {"name":"ID czynności","type":"INTEGER","def":"0","attr":""},
        {"name":"krotność wykonania","type":"FLOAT","def":"0","attr":""},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
    ]},
    {name: "zlecenia gaz", cols: [
        {"name":"ID zlecenia","type":"INTEGER","def":"0","attr":""},
        {"name":"ID czynności","type":"INTEGER","def":"0","attr":""},
        {"name":"krotność wykonania","type":"FLOAT","def":"0","attr":""},
        {"name":"cena netto","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
    ]},
    {name: "zlecenia instalacji gazowej", cols: [
        {"name":"ID","type":"INTEGER","attr":"pan"},
        {"name":"ID klienta","type":"INTEGER","def":"0","attr":""},
        {"name":"ID samochodu","type":"INTEGER","def":"0","attr":""},
        {"name":"data otwarcia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
        {"name":"data zamknięcia","type":"DATETIME","attr":""},
        {"name":"zysk z części","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"zysk z robocizny","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"mechanik prowadzący","type":"LONGTEXT","attr":""},
        {"name":"% udziału","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"pomocnik 1","type":"LONGTEXT","attr":""},
        {"name":"% udziału p1","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"pomocnik 2","type":"LONGTEXT","attr":""},
        {"name":"% udziału p2","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"zgłoszone naprawy","type":"LONGTEXT","attr":""},
        {"name":"uwagi o naprawie","type":"INTEGER","def":"0","attr":"n"},
    ]},
    {name: "zlecenia naprawy", cols: [
        {"name":"ID","type":"INTEGER","attr":"pan"},
        {"name":"ID klienta","type":"INTEGER","def":"0","attr":""},
        {"name":"ID samochodu","type":"INTEGER","def":"0","attr":""},
        {"name":"data otwarcia","type":"TIMESTAMP","def":"CURRENT_TIMESTAMP","attr":""},
        {"name":"data zamknięcia","type":"DATETIME","attr":""},
        {"name":"nr_faktury","type":"LONGTEXT","attr":"q"},
        {"name":"platnosc_forma","type":"LONGTEXT","attr":""},
        {"name":"platnosc_data","type":"DATETIME","attr":""},
        {"name":"zysk z części","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"zysk z robocizny","type":"DECIMAL","targ":"19,4","def":"0","attr":""},
        {"name":"mechanik prowadzący","type":"LONGTEXT","attr":""},
        {"name":"% udziału","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"pomocnik 1","type":"LONGTEXT","attr":""},
        {"name":"% udziału p1","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"pomocnik 2","type":"LONGTEXT","attr":""},
        {"name":"% udziału p2","type":"TINYINT","targ":"3","def":"0","attr":"u"},
        {"name":"zgłoszone naprawy","type":"LONGTEXT","attr":""},
        {"name":"uwagi o naprawie","type":"LONGTEXT","attr":""},
    ]},
]);

export {DB};